baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "My New Hugo Site"               # Site title. Appears above the menu, above the site description, if set.

[outputs]
home = ['html']

[[module.imports]]
path = "paige"

[params.paige.site]
date_format = ":date_long"      # Hugo date format
description = "Example site description"   # Site description. Appears above the menu, below the site title, if set.
external_link_new_tab = true    # Open external links in new tabs
keyword_style = "text"          # Must be "text" or "pills"
menu_style = "links"            # Must be "links", "pills", "tabs", or "underline"

disable_breadcrumbs = true
disable_copyright = true
disable_credit = true

[params.paige.pages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true
disable_word_count = true

[params.paige.subpages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true
disable_word_count = true

[markup.goldmark.renderer]
unsafe = true
